config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'
  get 'order_items/update'
  get 'order_items/destroy'
  get 'carts/show'
  get 'about/orderconfirmation'
  get 'about/makers'

  resources :charges
  resources :products do
    post :create
  end

  resources :about
  resources :orders
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  devise_for :users

  root to: 'products#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  def total_with_shipping
    subtotal + 5
  end

  def total_cents
    total_with_shipping * 100
  end


private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

  default_scope { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :products

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def orderconfirmation
  end

  def makers
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      order = Order.create
      session[:order_id] = order.id
      return order
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items

  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  protect_from_forgery :except => :webhook

  def new
  end

  def create
    customer = Stripe::Customer.create(
      :card  => params[:stripeToken],
      :email => params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => Integer(current_order.total_cents),
      :description => "Order ##{current_order.id}",
      :currency    => 'usd',
      :receipt_email => customer.email
    )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to charges_path
  end

  private
    def update_order_status
      current_order.order_status_id = 2;
    end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @order_item = @order.order_items.create(order_item_params)
    @order.save
    render :js => "window.location = '/cart';"
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
    redirect_to carts_path
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end
private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
    @orderitems = OrderItem.all
    @products = Product.all
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @order_item = current_order.order_items.new

  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to cart_path, notice: 'product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
    @order_item = current_order.order_items.new

  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :bead1, :bead2, :bead3, :bead4, :bead5, :bead6, :bead7, :bead8, :bead9, :bead10, :bead11, :strand, :length, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def destroy
  end
  
  def edit
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beads_helper.rb
module BeadsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clasp_helper.rb
module ClaspHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/strand_helper.rb
module StrandHelper
end

app/views/about/makers.html.erb
<div class="makers">

  <div class="makers--main">
    <h1>meet the <span class="sniglet">makers</span></h1>
    <div class="bio-christine bio">
      <h2>christine <span class="sniglet">cha</span></h2>
      <p>Bio coming soon.</p>
    </div>
    <div class="bio-kami bio">
      <h2><span class="waiting-for-the-sunrise">KAMI</span> maltz</h2>
      <p>Bio coming soon.</p>
    </div>
  </div>

</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67846181-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/about/orderconfirmation.html.erb
<div class="cart--banner">
  <h1>your <span class="sniglet">ORDER</span> has been <span class="waiting-for-the-sunrise">PLACED</span></h1>
  <h4>It'll be on its way shortly.</h4>
  <%= image_tag('graphics/heart_100x100.gif') %>
</div>

<div class="share-order">
  <div class="social-share">
    
  <div>
</div>

app/views/carts/_cart_row.html.erb
<div class="cart--product-container">
  <h4>
  <% if product.name? %>
    <%= product.name %>
  <% else %>
    untitled necklace
  <% end %>
  </h4>
  <br>
  <div class="designtool">
    <div class="necklace-view">
      <div class="beads">
        <div class="beads">
          <% if product.bead1? %>
            <%= image_tag "editor/beads/#{product.bead1}.png", class: "bead" %>
          <% end %>
          <% if product.bead2? %>
            <%= image_tag "editor/beads/#{product.bead2}.png", class: "bead" %>
          <% end %>
          <% if product.bead3? %>
            <%= image_tag "editor/beads/#{product.bead3}.png", class: "bead" %>
          <% end %>
          <% if product.bead4? %>
            <%= image_tag "editor/beads/#{product.bead4}.png", class: "bead" %>
          <% end %>
          <% if product.bead5? %>
            <%= image_tag "editor/beads/#{product.bead5}.png", class: "bead" %>
          <% end %>
          <% if product.bead6? %>
            <%= image_tag "editor/beads/#{product.bead6}.png", class: "bead" %>
          <% end %>
          <% if product.bead7? %>
            <%= image_tag "editor/beads/#{product.bead7}.png", class: "bead" %>
          <% end %>
          <% if product.bead8? %>
            <%= image_tag "editor/beads/#{product.bead8}.png", class: "bead" %>
          <% end %>
          <% if product.bead9? %>
            <%= image_tag "editor/beads/#{product.bead9}.png", class: "bead" %>
          <% end %>
          <% if product.bead10? %>
            <%= image_tag "editor/beads/#{product.bead10}.png", class: "bead" %>
          <% end %>
          <% if product.bead11? %>
            <%= image_tag "editor/beads/#{product.bead11}.png", class: "bead" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <br>
  <%= form_for order_item, remote: true do |f| %>
    <h5>
      UNIT PRICE: <%= number_to_currency order_item.unit_price %>
      &bull;
      TOTAL PRICE: <%= number_to_currency order_item.total_price %>
    </h5>
    <%= f.number_field :quantity, value: order_item.quantity.to_i, min: 1 %>
    <%= f.hidden_field :product_id, value: product.id %>
    <%= f.submit "UPDATE", class: "btn btn-primary", onClick: "history.go(0)" %>
    <%= link_to "REMOVE", order_item, { data: { confirm: "Are you sure you wish to delete this product from your cart? This cannot be undone. (Eek!)" }, method: :delete, remote: true, class: "btn btn-danger", onClick: "history.go(0)" } %>
  <% end %>

</div>

app/views/carts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>

  <div class="no-items">
    <p class="text-center">
      It looks like you haven't added anything to your cart yet.
    </p>
    <br>
    <%= image_tag 'graphics/blink_left.gif', class: 'blinkers' %>
    <%= button_to "CREATE YOUR FIRST MICHAKA", new_product_path, class: "bead-it-btn", method: :get %>
    <%= image_tag 'graphics/blink_right.gif', class: 'blinkers' %>
  </div>

<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="cart--banner">
  <h1>your <span class="sniglet">SHOPPIN'</span> <span class="waiting-for-the-sunrise">CART</span></h1>
  <h4>Your subtotal is <%= number_to_currency current_order.subtotal %>.</h4>
  <h4>+ $5 flat international shipping</h4>

  <br>
  <% if @order_items.size == 0 %>
  <% else %>
    <%= form_tag charges_path do %>
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="MICHAKA"
              data-amount="<%= current_order.total_cents %>"
              data-billingAddress="true"
              data-shippingAddress="true"
              data-locale="auto">
      </script>
    <% end %>
    <%= button_to "MAKE ANOTHER", new_product_path, class: "bead-it-btn", method: :get %>
  <% end %>

  <br>
</div>

<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67846181-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/charges/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/charges/create.html.erb
<div class="cart--banner">
  <h1>your <span class="sniglet">ORDER</span> has been <span class="waiting-for-the-sunrise">PLACED</span></h1>
  <h4>It'll be on its way shortly.</h4>
  <%= image_tag('graphics/heart_100x100.gif') %>
</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67846181-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= current_order.subtotal_cents %>"
          data-locale="auto"></script>
<% end %>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'carts/cart_text') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'carts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'carts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/orders/index.html.erb
<% @orders.where(:order_status => 1).each do |order| %>

  <div>
    <h1>placed order # <%= order.id %> </h1>

    <% @orderitems.where(:order_id => order.id).each do |orderitem| %>
      <h2> <%= orderitem.id %> x <%= orderitem.quantity %></h2>

      <% @products.where(:id => orderitem.product_id).each do |product| %>
        <p> <%= product.id %> </p>
        <p> <%= product.bead1 %> </p>
        <p> <%= product.bead2 %> </p>
        <p> <%= product.bead3 %> </p>
        <p> <%= product.bead4 %> </p>
        <p> <%= product.bead5 %> </p>
        <p> <%= product.bead6 %> </p>
        <p> <%= product.bead7 %> </p>
        <p> <%= product.bead8 %> </p>
        <p> <%= product.bead9 %> </p>
        <p> <%= product.bead10 %> </p>
        <p> <%= product.bead11 %> </p>
      <% end %>

    <% end %>
  </div>

<% end %>

app/views/products/_beadpicker.html.erb
<div class="beadOptions">

  <br>
  <div class="custom-dropdown shapePicker">
    <div class="selector">
      <p>SHAPE</p>
    </div>
    <div class="dropdown">
      <div class="option selected">square</div>
      <div class="option">tube</div>
      <div class="option">big round</div>
      <div class="option">small round</div>
      <div class="option">flat</div>
    </div>
  </div>
  <div class="custom-dropdown patternPicker">
    <div class="selector">
      <p>PATTERN</p>
    </div>
    <div class="dropdown">
      <div class="option selected">solid</div>
      <div class="option">sprinkles</div>
      <div class="option">polka dots</div>
      <div class="option">marbled</div>
    </div>
  </div>
  <div class="custom-dropdown colorPicker">
    <div class="selector">
      <p>COLOR</p>
    </div>
    <div class="dropdown">
      <div class="option">black</div>
      <div class="option selected">white</div>
    </div>
  </div>


  <br>
  <br>
  <div class="removeBead">
    <i class="fa fa-times-circle-o "></i><h4>REMOVE BEAD</h5>
  </div>
</div>

app/views/products/_designtoolguide.html.erb
<div class="designtool--guide">

  <div class="label labels--name">
    <h4>
      <i class="fa fa-arrow-circle-up"></i>
      This is where you <strong>title</strong> your masterpiece.
    </h4>
  </div>

  <div class="label labels--strand">
    <h4>
      <i class="fa fa-heart-o"></i>
      Pick a <strong>strand style</strong> that suits you!
    </h4>
  </div>

  <div class="label labels--length">
    <h4>
      <i class="fa fa-long-arrow-left"></i>
      <i class="fa fa-long-arrow-right"></i>
      The longer length (80cm) is <strong>$2</strong> extra.
    </h4>
  </div>

  <div class="label labels--quantity">
    <h4>
      <i class="fa fa-question-circle"></i>
      How many do you want to order?
    </h4>
  </div>

  <div class="label labels--price">
    <h4>
      <i class="fa fa-truck"></i>
      + $5 flat international shipping. Yay!
    </h4>
  </div>

  <div class="label labels--removeBead">
    <h4>
      <i class="fa fa-exclamation-circle"></i>
      You have to have at least one bead!
    </h4>
  </div>

</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="beadPicker">
  </div>

  <div class="field">
    <%= f.label :bead1 %><br>
    <%= f.text_field :bead1, style: "display:none;"%><br>
    <p>Shape</p>
    <select id="shapePicker">
      <%= options_for_select([["square"], "donut"]) %>
    </select>
    <p>Shape</p>
    <select id="patternPicker">
      <%= options_for_select([["solid"], "sprinkles"]) %>
    </select>
    <br>
    <input type="checkbox" name="hide" value="hidden" id="beadToggle">Remove Bead<br>
  </div>
  <div class="field">
    <%= f.label :bead2 %><br>
    <%= f.text_field :bead2 %>
  </div>
  <div class="field">
    <%= f.label :bead3 %><br>
    <%= f.text_field :bead3 %>
  </div>
  <div class="field">
    <%= f.label :bead4 %><br>
    <%= f.text_field :bead4 %>
  </div>
  <div class="field">
    <%= f.label :bead5 %><br>
    <%= f.text_field :bead5 %>
  </div>
  <div class="field">
    <%= f.label :bead6 %><br>
    <%= f.text_field :bead6 %>
  </div>
  <div class="field">
    <%= f.label :bead7 %><br>
    <%= f.text_field :bead7 %>
  </div>
  <div class="field">
    <%= f.label :bead8 %><br>
    <%= f.text_field :bead8 %>
  </div>
  <div class="field">
    <%= f.label :bead9 %><br>
    <%= f.text_field :bead9 %>
  </div>
  <div class="field">
    <%= f.select :strand, options_for_select([["Black & White"], "Black"]) %>
    <%= f.label :strand %><br>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product_row.html.erb
<div class="cart--product-container">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true, product: product do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="homepage">

  <div class="splash">
    <div class="text-block">
      <%= image_tag 'logos/michaka.png', class: 'logo' %>
      <h1>classic. <span class="sniglet">funky. </span><span class="waiting-for-the-sunrise">HANDMADE.</span></h1>
      <br>
      <%= image_tag 'graphics/blink_left.gif', class: 'blinkers' %>
      <%= button_to "BEAD IT", new_product_path, class: "bead-it-btn", method: :get %>
      <%= image_tag 'graphics/blink_right.gif', class: 'blinkers' %>
    </div>
  </div>

  <div class="featured-designs">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag('photos/IMG_0121.png') %>
        <%= button_to 'GET INSPIRED', 'https://instagram.com/michakajewelry', class: 'bead-it-btn', form: {target: '_blank'} %>
      </div>
      <div class="col-md-4">
        <%= image_tag('photos/IMG_0120.png') %>
        <%= button_to 'MEET THE MAKERS', about_makers_path, class: 'bead-it-btn', method: :get %>
      </div>
      <div class="col-md-4">
        <%= image_tag('photos/IMG_0123.png') %>
        <%= button_to 'BEAD YOUR OWN', new_product_path, method: :get, class: 'bead-it-btn' %>
      </div>
    </div>
    <br>
    <hr>
    <br>
    <%= image_tag('graphics/heart_100x100.gif') %>
    <h3>&#35;michaka</h3>
  </div>


</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67846181-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Bead1:</strong>
  <%= @product.bead1 %>
</p>

<p>
  <strong>Bead2:</strong>
  <%= @product.bead2 %>
</p>

<p>
  <strong>Bead3:</strong>
  <%= @product.bead3 %>
</p>

<p>
  <strong>Bead4:</strong>
  <%= @product.bead4 %>
</p>

<p>
  <strong>Bead5:</strong>
  <%= @product.bead5 %>
</p>

<p>
  <strong>Bead6:</strong>
  <%= @product.bead6 %>
</p>

<p>
  <strong>Bead7:</strong>
  <%= @product.bead7 %>
</p>

<p>
  <strong>Bead8:</strong>
  <%= @product.bead8 %>
</p>

<p>
  <strong>Bead9:</strong>
  <%= @product.bead9 %>
</p>

<p>
  <strong>Strand:</strong>
  <%= @product.strand %>
</p>

<p>
  <strong>Length:</strong>
  <%= @product.length %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>